name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**/*.php"
      - "**/*.css"
      - "**/*.js"
      - "style.css"
      - "functions.php"
      - "theme.json"

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-sonnet-4-20250514"
          direct_prompt: |
            Please review this WordPress child theme pull request and provide feedback on:
            
            **WordPress-Specific Concerns:**
            - WordPress coding standards compliance (WordPress, PSR-12)
            - Proper use of WordPress hooks and filters
            - Child theme best practices (proper parent theme enqueuing, etc.)
            - Security concerns (sanitization, validation, nonces)
            - Performance considerations (database queries, caching)
            - Accessibility compliance (WCAG 2.1 AA standards)
            
            **Theme Development:**
            - Proper theme structure and file organization
            - Block editor (Gutenberg) compatibility
            - WooCommerce integration best practices
            - Responsive design considerations
            - Cross-browser compatibility
            
            **Code Quality:**
            - PHP 8.0+ compatibility
            - Proper error handling
            - Code documentation and comments
            - Function and variable naming conventions
            - Potential bugs or logic issues
            
            **CSS/Frontend:**
            - CSS best practices and organization
            - Performance optimization
            - Mobile-first responsive design
            - Proper use of WordPress theme.json
            
            Please be constructive and provide specific suggestions for improvement.
            Focus on WordPress-specific best practices and security considerations.
            
            If this is from a first-time contributor, be encouraging and provide detailed explanations.

      - name: Theme Structure Validation
        run: |
          echo "Validating WordPress theme structure..."
          
          # Check required files
          REQUIRED_FILES=("style.css" "functions.php")
          for file in "${REQUIRED_FILES[@]}"; do
            if [[ ! -f "$file" ]]; then
              echo "❌ Missing required file: $file"
              exit 1
            fi
          done
          
          # Check style.css header
          if ! grep -q "Theme Name:" style.css; then
            echo "❌ style.css missing Theme Name header"
            exit 1
          fi
          
          if ! grep -q "Template:" style.css; then
            echo "❌ style.css missing Template header (required for child themes)"
            exit 1
          fi
          
          echo "✅ Theme structure validation passed"
