name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies
        run: npm install

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Validate theme
        run: npm run validate

      - name: Create theme ZIP
        run: |
          # Create a temporary directory for the theme
          mkdir -p /tmp/blazecommerce-child
          
          # Copy theme files (exclude development files)
          rsync -av \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='node_modules/' \
            --exclude='package*.json' \
            --exclude='scripts/' \
            --exclude='tests/' \
            --exclude='phpunit.xml' \
            --exclude='coverage/' \
            --exclude='.augment*' \
            --exclude='docs/' \
            --exclude='*.log' \
            --exclude='.vscode/' \
            --exclude='.idea/' \
            --exclude='.DS_Store' \
            --exclude='Thumbs.db' \
            . /tmp/blazecommerce-child/
          
          # Create the ZIP file
          cd /tmp
          zip -r blazecommerce-child-${{ steps.version.outputs.VERSION }}.zip blazecommerce-child/
          
          # Move ZIP back to workspace
          mv blazecommerce-child-${{ steps.version.outputs.VERSION }}.zip $GITHUB_WORKSPACE/

      - name: Generate release notes
        id: release_notes
        run: |
          # Extract changelog for this version
          if [ -f CHANGELOG.md ]; then
            # Get content between this version and next version header
            awk '/^## \[${{ steps.version.outputs.VERSION }}\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md > release_notes.txt
            echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
            cat release_notes.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_NOTES=Release version ${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          files: |
            blazecommerce-child-${{ steps.version.outputs.VERSION }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload theme to WordPress.org (if configured)
        if: ${{ secrets.WP_ORG_USERNAME && secrets.WP_ORG_PASSWORD }}
        run: |
          echo "WordPress.org deployment would happen here"
          echo "Theme ZIP: blazecommerce-child-${{ steps.version.outputs.VERSION }}.zip"
          # Add WordPress.org SVN deployment logic here if needed
